# -*- coding: utf-8 -*-
"""final11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbIXjeBwhm_sULj-l9fUjKMYe0WoU65i
"""

#โปรแกรมคำนวณเกรดจากคะแนน (A/B/C/D/F)

score = float(input("ใส่คะแนนของคุณ: "))

if score >= 80:
   grade = "A"
elif score  >= 70:
   grade = "B"
elif  score  >= 60:
   grade = "C"
elif  score  >= 50:
   grade = "D"
else :
   grade = "F"

print("คะแนนของคุณคือ: "+ grade )

#โดยนายภานุวัฒน์ เต้จัน ม.4/4 เลขที่ 11